extends:
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 2019
  ecmaFeatures:
    impliedStrict: true
    jsx: true
  sourceType: module
env:
  browser: true
  node: true
  shared-node-browser: true
